Repository ice-cream-the-fat-cat/my-niwa-frontend, pull requests merged in 2021-09, with the labels that each got.

#59 Add animations to creategarden
  package.json
  src/pages/CreateGarden/components/AddRules.tsx
  src/pages/CreateGarden/components/GardenSummary.tsx
  src/pages/CreateGarden/components/NewGarden.tsx
  src/pages/CreateGarden/index.tsx
  yarn.lock
Labels: need discussion

#81 [Feature] Add loading component wrapper and some refactoring
  src/App.tsx
  src/components/AppWrapper/index.tsx
  src/components/Header/Header.css
  src/components/Header/Header.module.css
  src/components/Header/index.tsx
  src/components/LoadingWrapper/Loading.tsx
  src/components/LoadingWrapper/LoadingWrapper.module.css
  src/components/LoadingWrapper/index.tsx
  src/components/SignIn/useFirebaseAuth.tsx
  src/index.css
  src/pages/CreateGarden/index.tsx
  src/pages/GardenView/index.tsx
  src/pages/Home/home.css
  src/pages/Home/index.tsx
  src/pages/MyGardens/index.tsx
  src/pages/NotFound/NotFound.module.css
  src/pages/NotFound/assets/not-found1.gif
  src/pages/NotFound/assets/not-found2.gif
  src/pages/NotFound/index.tsx
  src/routes.tsx
  src/store/user/UserStateAtoms.ts
Labels: review wanted

#78 Feature top page implementation
  src/components/SignIn/index.tsx
  src/pages/About/About.css
  src/pages/About/index.tsx
  src/pages/CreateGarden/components/AddRules.css
  src/pages/Home/home.css
  src/pages/Home/index.tsx
  src/routes.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#82 [Feature] Replace moment with datefns
  package.json
  src/models/completedTask.model.tsx
  src/pages/GardenView/index.tsx
  yarn.lock
Labels: review wanted

#79 Feature add bottom navbar
  src/components/BottomNav/index.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/GardenView/index.tsx
  src/routes.tsx
Labels: need discussion, review wanted

#90 About page relinked
  src/routes.tsx
Labels: review wanted

#86 Feature refactor create garden
  src/components/BottomNav/index.tsx
  src/components/Header/Header.module.css
  src/components/Header/index.tsx
  src/components/UserViewLayout/UserViewLayout.module.css
  src/components/UserViewLayout/index.tsx
  src/pages/About/index.tsx
  src/pages/CreateGarden/CreateGardenPage.css
  src/pages/CreateGarden/components/AddRules.css
  src/pages/CreateGarden/components/AddRules.tsx
  src/pages/CreateGarden/components/GardenSummary.css
  src/pages/CreateGarden/components/GardenSummary.tsx
  src/pages/CreateGarden/components/NewGarden.css
  src/pages/CreateGarden/components/NewGarden.tsx
  src/pages/CreateGarden/components/UserRule.css
  src/pages/CreateGarden/components/UserRule.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/MyGardens/index.tsx
  src/routes.tsx
  src/utils/UITheme.tsx
Labels: review wanted

#94 fix .vscode config to use prettier correctly
  .vscode/settings.json
Labels: review wanted

#95 [Feature] add user image
  src/components/Header/Header.module.css
  src/components/Header/assets/hamburger.svg
  src/components/Header/index.tsx
  src/index.css
  src/pages/GardenView/index.tsx
  src/pages/Home/home.css
  src/routes.tsx
  src/store/user/UserStateAtoms.ts
Labels: review wanted

#91 Updating Garden View to fit current design
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/DailyGardening.css
  src/pages/DailyGardening/assets/watering.gif
  src/pages/DailyGardening/index.tsx
  src/pages/MyGardens/MyGardens.css
  src/pages/MyGardens/index.tsx
  src/routes.tsx
  src/store/user/UserStateAtoms.ts
Labels: review wanted

#99 Feature fix animations
  src/pages/About/index.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyGardens/index.tsx
  src/pages/NotFound/index.tsx
  src/routes.tsx
Labels: review wanted

#93 Fix garden's model to fireBaseUserId to match completedTask's model (Can be pushed after Saturday's demo)
  src/models/garden.model.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/index.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#118 Feature add api fix to staging
  docs/branches_and_environments.md
  src/models/garden.model.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/index.tsx
Labels: review wanted

#121 Connect delete completedTask with API
  src/pages/DailyGardening/index.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#122 [Feature] Refactor each page logic and prevent multiple calls
  src/helpers/api/completedTasks/deleteCompletedTask.ts
  src/helpers/api/completedTasks/sendCompletedTask.ts
  src/helpers/api/gardens/getGardenByGardenId.ts
  src/helpers/api/gardens/getGardens.ts
  src/models/completedTask.model.tsx
  src/models/garden.model.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/index.tsx
  src/pages/MyGardens/index.tsx
  src/utils/api/index.ts
  src/utils/api/useApi.ts
Labels: Priority: HIGH 🏃‍♂️💨, review wanted, refactoring

#124 Feature reorganize bottom nav links
  src/components/BottomNav/index.tsx
  src/components/UserViewLayout/index.tsx
  src/pages/MyGardens/index.tsx
Labels: review wanted

#127 Add styling to tooltip
  src/pages/MyGardens/index.tsx
Labels: review wanted

#129 Renamed mygardens to myniwa
  src/assets/sunflowerlogo.png
  src/components/BottomNav/index.tsx
  src/components/SignIn/index.tsx
  src/components/UserViewLayout/index.tsx
  src/pages/About/index.tsx
  src/pages/DailyGardening/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyNiwa/MyNiwa.css
  src/pages/MyNiwa/assets/garden1.jpg
  src/pages/MyNiwa/assets/garden2.jpg
  src/pages/MyNiwa/index.tsx
  src/routes.tsx
Labels: review wanted

#134 [Feature] Refactor create garden page
  mockServer/data/gardens/gardenData.ts
  mockServer/data/gardens/gardensData.ts
  mockServer/data/gardens/newGardenData.ts
  mockServer/data/gardensData.ts
  mockServer/data/rules/rulesBulkData.ts
  mockServer/data/tmpData.ts
  mockServer/routes/gardens/index.ts
  mockServer/routes/rules/index.ts
  mockServer/routes/tmp/index.ts
  mockServer/server.ts
  src/helpers/api/completedTasks/sendCompletedTask.ts
  src/helpers/api/gardens/createGarden.ts
  src/helpers/api/gardens/createGardenRules.ts
  src/models/completedTask.model.ts
  src/models/garden.model.ts
  src/models/rule.model.ts
  src/pages/CreateGarden/components/AddRules.tsx
  src/pages/CreateGarden/components/GardenSummary.tsx
  src/pages/CreateGarden/index.tsx
Labels: review wanted

#132 Send converted UTC date for completedTask date field
  src/helpers/api/gardens/getGardenByGardenId.ts
  src/pages/DailyGardening/index.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#138 [Feature] Get account data
  mockServer/data/users/userAccountData.ts
  mockServer/routes/users/index.ts
  mockServer/server.ts
  package.json
  src/components/AppWrapper/index.tsx
  src/components/Header/Header.module.css
  src/components/Header/assets/coin.png
  src/components/Header/index.tsx
  src/components/SignIn/useFirebaseAuth.tsx
  src/helpers/api/users/getUserAccountData.ts
  src/models/flower.model.ts
  src/models/user.model.ts
  src/pages/CreateGarden/components/AddRules.tsx
  src/pages/MyNiwa/index.tsx
  src/store/user/UserStateAtoms.ts
  yarn.lock
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#133 Feature splash and about page styling
  src/pages/About/About.css
  src/pages/About/assets/garden.gif
  src/pages/About/index.tsx
  src/pages/Home/home.css
  src/pages/Home/index.tsx
Labels: review wanted

#140 change numCoins to balance
  mockServer/data/users/userAccountData.ts
  src/components/AppWrapper/index.tsx
  src/components/Header/index.tsx
  src/components/SignIn/useFirebaseAuth.tsx
  src/models/user.model.ts
  src/store/user/UserStateAtoms.ts
Labels: review wanted

#144 fix material ui issue, still have strict mode warning
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#145 fixed top page layout
  src/pages/Home/home.css
Labels: review wanted

#137 Feature add store page
  mockServer/data/flowers/flowerStoreData.ts
  mockServer/data/flowers/flowersData.ts
  mockServer/data/users/userAccountData.ts
  mockServer/nodemon.json
  mockServer/routes/flowerStore/index.ts
  mockServer/routes/flowers/index.ts
  mockServer/server.ts
  src/components/Header/index.tsx
  src/helpers/api/flowers/buyFlower.ts
  src/helpers/api/flowers/getFlowers.ts
  src/models/flower.model.ts
  src/models/user.model.ts
  src/pages/Florist/Florist.module.css
  src/pages/Florist/FloristWithCart/FloristWithCart.tsx
  src/pages/Florist/assets/questionMark.png
  src/pages/Florist/index.tsx
  src/routes.tsx
  src/store/user/UserStateAtoms.ts
Labels: review wanted

#151 Adjust UI based on feedback
  src/pages/About/index.tsx
  src/pages/Home/home.css
  src/pages/Home/index.tsx
  src/pages/MyNiwa/MyNiwa.css
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#147 Feature add categories to flower beds
  src/helpers/api/gardens/getCategories.ts
  src/models/category.model.ts
  src/pages/CreateGarden/components/GardenSummary.tsx
  src/pages/CreateGarden/components/NewGarden.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/DailyGardening.css
  src/pages/Home/home.css
  src/pages/MyNiwa/MyNiwa.css
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#165 Feature update completed task
  mockServer/data/completedTask/index.ts
  mockServer/routes/completedTask/index.ts
  mockServer/server.ts
  src/helpers/api/completedTasks/sendCompletedTask.ts
  src/models/user.model.ts
  src/pages/DailyGardening/index.tsx
  src/utils/api/index.ts
Labels: review wanted

#166 Merge dev to staging sprint03.1
  mockServer/data/completedTask/index.ts
  mockServer/routes/completedTask/index.ts
  mockServer/server.ts
  src/helpers/api/completedTasks/sendCompletedTask.ts
  src/models/user.model.ts
  src/pages/DailyGardening/index.tsx
  src/utils/api/index.ts
Labels: review wanted

#154 add loading wrapper to tasks
  src/pages/DailyGardening/index.tsx
Labels: review wanted

#184 [Feature] Update coins balance when completing a task
  mockServer/data/completedTask/index.ts
  mockServer/routes/completedTask/index.ts
  src/pages/DailyGardening/index.tsx
Labels: review wanted

#182 add message if use has not coin
  src/pages/Florist/index.tsx
Labels: review wanted

#180 add message for user has no Niwa
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#177 Feature display categories on garden summary
  src/pages/About/index.tsx
  src/pages/CreateGarden/components/GardenSummary.tsx
  src/pages/CreateGarden/components/NewGarden.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#175 Small UI improvements (please see description for list of tasks)
  src/App.tsx
  src/index.css
  src/pages/About/About.module.css
  src/pages/About/index.tsx
  src/pages/Home/Home.module.css
  src/pages/Home/index.tsx
  src/pages/MyNiwa/MyNiwa.css
Labels: Priority: MEDIUM👾, review wanted

#186 Feature adjust daily gardening layout
  src/pages/DailyGardening/DailyGardening.css
  src/pages/DailyGardening/DailyGardening.module.css
  src/pages/DailyGardening/index.tsx
Labels: review wanted

#200 Fix bottom nav on page change
  .vscode/settings.json
  src/components/UserViewLayout/index.tsx
  src/models/flower.model.ts
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/index.tsx
  src/pages/Florist/FloristWithCart/FloristWithCart.tsx
  src/pages/MyNiwa/index.tsx
  src/store/page/PageStateAtoms.ts
  src/store/page/usePageState.ts
Labels: review wanted

#201 Fix bottom nav buttons
  src/components/BottomNav/index.tsx
  src/components/UserViewLayout/UserViewLayout.module.css
  src/components/UserViewLayout/index.tsx
Labels: need discussion, review wanted

#204 [Feature] Add basic pwa
  public/favicon.ico
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/index.tsx
Labels: need discussion, review wanted

#143 [Feature] Implement garden setting page and some ui component refactoring
  mockServer/data/gardens/gardenData.ts
  mockServer/data/gardens/gardensData.ts
  mockServer/data/tasks/completedTask.ts
  mockServer/routes/gardens/index.ts
  mockServer/routes/tasks/index.ts
  package.json
  src/App.tsx
  src/components/BottomNav/index.tsx
  src/components/Head/index.tsx
  src/components/Header/Header.module.css
  src/components/Header/index.tsx
  src/components/LoadingWrapper/Loading.tsx
  src/components/LoadingWrapper/LoadingWrapper.module.css
  src/components/Section/Section.module.css
  src/components/Section/index.tsx
  src/components/SectionTitle/SectionTitle.module.css
  src/components/SectionTitle/index.tsx
  src/components/UserViewLayout/UserViewLayout.module.css
  src/components/UserViewLayout/index.tsx
  src/helpers/api/gardens/createGarden.ts
  src/helpers/api/gardens/updateGardenData.ts
  src/models/garden.model.ts
  src/pages/About/index.tsx
  src/pages/CreateGarden/index.tsx
  src/pages/DailyGardening/DailyGardening.module.css
  src/pages/DailyGardening/index.tsx
  src/pages/Florist/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyNiwa/MyNiwa.css
  src/pages/MyNiwa/MyNiwa.module.css
  src/pages/MyNiwa/index.tsx
  src/pages/NotFound/NotFound.module.css
  src/pages/NotFound/index.tsx
  src/pages/Settings/Settings.module.css
  src/pages/Settings/components/DescriptionInput/DescriptionInput.module.css
  src/pages/Settings/components/DescriptionInput/index.tsx
  src/pages/Settings/components/GardenDataWrapper/GardenDataWrapper.module.css
  src/pages/Settings/components/GardenDataWrapper/index.tsx
  src/pages/Settings/components/NameInput/NameInput.module.css
  src/pages/Settings/components/NameInput/index.tsx
  src/pages/Settings/index.tsx
  src/routes.tsx
  yarn.lock
Labels: review wanted

#209 [Feature] Implement category and rules edit and some other small fixes
  mockServer/data/gardens/gardenData.ts
  mockServer/routes/gardens/index.ts
  src/helpers/api/gardens/updateGardenData.ts
  src/pages/CreateGarden/index.tsx
  src/pages/Settings/components/CategorySelector/CategorySelector.module.css
  src/pages/Settings/components/CategorySelector/index.tsx
  src/pages/Settings/components/DescriptionInput/DescriptionInput.module.css
  src/pages/Settings/components/DescriptionInput/index.tsx
  src/pages/Settings/components/GardenDataWrapper/index.tsx
  src/pages/Settings/components/NameInput/NameInput.module.css
  src/pages/Settings/components/NameInput/index.tsx
  src/pages/Settings/index.tsx
Labels: review wanted

#202 add store confirm flow
  src/pages/Florist/Florist.module.css
  src/pages/Florist/component/dialog.tsx
  src/pages/Florist/index.tsx
Labels: Priority: MEDIUM👾, review wanted

#213 Fixed (?) bug in daily gardening
  src/pages/DailyGardening/index.tsx
Labels: bug, Priority: HIGH 🏃‍♂️💨, review wanted

#206 my Collection View
  src/components/BottomNav/index.tsx
  src/pages/MyCollection/MyCollection.css
  src/pages/MyCollection/assets/bird-cells.svg
  src/pages/MyCollection/assets/croppedbg.jpg
  src/pages/MyCollection/assets/tallgrass.png
  src/pages/MyCollection/index.tsx
  src/routes.tsx
Labels: review wanted

#216 [Feature] Implement edit garden rules(seeds)
  mockServer/data/gardens/gardenData.ts
  mockServer/routes/rules/index.ts
  src/App.test.tsx
  src/components/Section/Section.module.css
  src/components/UserViewLayout/UserViewLayout.module.css
  src/helpers/api/gardens/createGardenRules.ts
  src/helpers/api/gardens/updateGardenData.ts
  src/helpers/api/gardens/updateGardenRule.ts
  src/pages/DailyGardening/DailyGardening.module.css
  src/pages/DailyGardening/index.tsx
  src/pages/Settings/Settings.module.css
  src/pages/Settings/components/CategorySelector/CategorySelector.module.css
  src/pages/Settings/components/CategorySelector/index.tsx
  src/pages/Settings/components/CreateSeedModal/index.tsx
  src/pages/Settings/components/DescriptionInput/DescriptionInput.module.css
  src/pages/Settings/components/DescriptionInput/index.tsx
  src/pages/Settings/components/NameInput/NameInput.module.css
  src/pages/Settings/components/NameInput/index.tsx
  src/pages/Settings/components/SeedList/SeedList.module.css
  src/pages/Settings/components/SeedList/index.tsx
  src/pages/Settings/index.tsx
  src/routes.tsx
  src/utils/objectDeepEqual/index.ts
  src/utils/objectDeepEqual/objectDeepEqual.test.ts
Labels: review wanted

#215 Fix create garden layout
  src/components/UserViewLayout/UserViewLayout.module.css
  src/pages/CreateGarden/components/AddRules.tsx
  src/pages/CreateGarden/components/CGTitle.tsx
  src/pages/CreateGarden/components/GardenSummary.tsx
  src/pages/CreateGarden/components/NewGarden.tsx
  src/pages/CreateGarden/index.tsx
Labels: review wanted

#210 Feature add my growth
  package.json
  src/helpers/api/gardens/getGardenByGardenIdWithDates.ts
  src/models/completedTaskByGardenID.ts
  src/pages/MyGrowth/MyGrowth.module.css
  src/pages/MyGrowth/components/TabData.tsx
  src/pages/MyGrowth/components/TabPanel.tsx
  src/pages/MyGrowth/index.tsx
  src/routes.tsx
  yarn.lock
Labels: review wanted

#220 Fix scroll for mobile in My Growth
  src/pages/MyGrowth/index.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#221 Develop to Staging to fix scroll issue
  src/pages/MyGrowth/index.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#236 Fix heat map labels and prevent image to be draggable
  src/pages/Florist/index.tsx
  src/pages/MyGrowth/components/TabData.tsx
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#240 fixed flower display
  src/pages/MyCollection/index.tsx
Labels: review wanted

#241 [Fix] Make naming consistent && fix button on hover colours
  src/components/BottomNav/index.tsx
  src/pages/About/index.tsx
  src/pages/DailyGardening/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#239 [Feature] Change completed tasks UI to checkbox
  mockServer/routes/completedTask/index.ts
  src/helpers/api/completedTasks/deleteCompletedTask.ts
  src/pages/DailyGardening/DailyGardening.module.css
  src/pages/DailyGardening/index.tsx
Labels: review wanted

#237 Add coin icons on Florist store
  src/pages/Florist/Florist.module.css
  src/pages/Florist/assets/coin.png
  src/pages/Florist/component/dialog.tsx
  src/pages/Florist/index.tsx
Labels: Priority: LOW💩, review wanted

#238 Fix bottom nav
  public/index.html
  src/components/BottomNav/index.tsx
  src/components/Header/Header.module.css
  src/components/Header/index.tsx
  src/components/UserViewLayout/UserViewLayout.module.css
Labels: need discussion, review wanted

#242 fixed florist display issues
  src/pages/Florist/Florist.module.css
  src/pages/Florist/component/dialog.tsx
  src/pages/Florist/index.tsx
Labels: review wanted

#243 add loading wrapper to collections page
  src/pages/MyCollection/index.tsx
Labels: review wanted

#244 Merge develop to staging for demo day rehearsal
  mockServer/routes/completedTask/index.ts
  public/index.html
  src/components/BottomNav/index.tsx
  src/components/Header/Header.module.css
  src/components/Header/index.tsx
  src/components/LoadingWrapper/CustomSpinner.module.css
  src/components/LoadingWrapper/CustomSpinner.tsx
  src/components/LoadingWrapper/Loading.tsx
  src/components/LoadingWrapper/LoadingWrapper.module.css
  src/components/LoadingWrapper/assets/myniwa.svg
  src/components/LoadingWrapper/index.tsx
  src/components/UserViewLayout/UserViewLayout.module.css
  src/helpers/api/completedTasks/deleteCompletedTask.ts
  src/pages/About/index.tsx
  src/pages/DailyGardening/DailyGardening.module.css
  src/pages/DailyGardening/index.tsx
  src/pages/Florist/Florist.module.css
  src/pages/Florist/assets/coin.png
  src/pages/Florist/component/dialog.tsx
  src/pages/Florist/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyGrowth/components/TabData.tsx
  src/pages/MyNiwa/index.tsx
Labels: review wanted

#245 fix custom loader
  mockServer/routes/completedTask/index.ts
  src/components/BottomNav/index.tsx
  src/components/LoadingWrapper/CustomSpinner.tsx
  src/components/LoadingWrapper/LoadingWrapper.module.css
  src/components/LoadingWrapper/index.tsx
  src/pages/About/index.tsx
  src/pages/DailyGardening/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyGrowth/components/TabPanel.tsx
Labels: review wanted
